// src/features/location/LocationImage.tsx
import { Mountain } from './Mountain';
import { Center } from './Center';
import { Beach } from './Beach';
import styles from './Location.module.css';

interface Props {
    name: string;
}

export const LocationImage = ({ name }: Props) => {

    const imageMap: { [key: string]: JSX.Element } = {
        beach: <Beach />,
        center: <Center />,
        mountain: <Mountain />
    };
    return (
        <svg className={ styles.image } preserveAspectRatio="xMinYMid slice" viewBox="0 0 844 390" xmlns="http://www.w3.org/2000/svg">
            { imageMap[name] }
        </svg>
    );
}

// src/lib/components/location/LocationImage.svelte
<script lang="ts">
	import styles from './Location.module.css';

	import Beach from './Beach.svelte';
	import Center from './Center.svelte';
	import Mountain from './Mountain.svelte';

	export let name: string;

	$: LocationComponent =
		name === 'beach' ? Beach : name === 'center' ? Center : name === 'mountain' ? Mountain : null;
</script>

<svg
	class={styles.image}
	preserveAspectRatio="xMinYMid slice"
	viewBox="0 0 844 390"
	xmlns="http://www.w3.org/2000/svg"
>
	{#if LocationComponent}
		<svelte:component this={LocationComponent} />
	{/if}
</svg>
