// src/lib/components/today/Today.svelte
<script lang="ts">
	import styles from './Today.module.css';

	import DayImage from '../layout/DayImage.svelte';
	import Bevel from '../layout/Bevel.svelte';

	import { locations } from '../location/locations';
	import { baseURL } from '../../../lib/api/api';
	import type { Today as TodayModel, TodayApiResponse } from '../../types/today';
	import { route } from '../../store/router';

	let today: TodayModel | undefined;
	let loading = false;
	let error: string | undefined;

	$: locationId = $route.locationId;
	$: location = locations.find((l) => l.url === locationId);
	$: lat = location?.lat;
	$: lon = location?.lon;

	const fetchToday = async (latitude: number, longitude: number) => {
		loading = true;
		error = undefined;
		try {
			const response = await fetch(
				`${baseURL}/weather?lat=${latitude}&lon=${longitude}&units=metric`
			);
			const data: TodayApiResponse = await response.json();
			today = data;
		} catch (e) {
			error = e instanceof Error ? e.message : String(e);
		} finally {
			loading = false;
		}
	};

	let lastFetchKey = '';
	$: {
		const key = lat != null && lon != null ? `${lat},${lon}` : '';
		if (key && key !== lastFetchKey) {
			lastFetchKey = key;
			fetchToday(lat!, lon!);
		}
	}
</script>

{#if location}
	<div class={styles.today}>
		<h1 class={styles.title}>Now in {location.label ?? ''}</h1>
		<div class={styles.container}>
			<div class={styles.bg}>
				<DayImage name={today?.weather?.[0]?.id?.toString() ?? ''} />
			</div>
			<div class={styles.frame}>
				<Bevel match={true} />
				<div class={styles.secondary}>
					<span>{today?.main.temp_min}º</span>
				</div>
				<div class={styles.main}>
					<span>{today?.main.temp}º</span>
				</div>
				<div class={styles.tertiary}>
					<span>{today?.main.temp_max}º</span>
				</div>
			</div>
		</div>
	</div>
{/if}

// src/features/today/Today.tsx
import { useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import { useParams } from 'react-router-dom';
import { DayImage } from '../../app/layout/DayImage';
import { locations } from '../location/locations';
import { useTodayStore } from '../../app/context/today-context';
import styles from './Today.module.css';
import { Bevel } from '../../app/layout/Bevel';

export const Today = observer(() => {
    const { locationId } = useParams();
    const location = locations.find(location => location.url === locationId);
    if (!location) return <></>
    const { lat, lon } = location;

    const { fetchToday, today } = useTodayStore();

    useEffect(() => {
        fetchToday(lat, lon);
    }, [fetchToday, lat, lon]);

    return (
        <div className={ styles.today }>
            <h1 className={ styles.title }>
                { 
                    `Now in ${ location.label ?? '' }`
                }
            </h1>
            <div className={ styles.container }>
                <div className={ styles.bg }>
                    <DayImage name={today?.weather[0].id.toString() ?? ''} />
                </div>
                <div className={ styles.frame }>
                    <Bevel match />
                    <div className={ styles.secondary }>
                        <span>{ today?.main.temp_min}º</span>
                    </div>
                    <div className={ styles.main }>
                        <span>{ today?.main.temp}º</span>
                    </div>
                    <div className={ styles.tertiary }>
                        <span>{ today?.main.temp_max}º</span>
                    </div>
                </div>
            </div>
        </div>
    );
});
