// src/lib/components/location/Location.svelte
<script lang="ts">
    import { locations } from './locations';
    import styles from './Location.module.css';
    import LocationImage from './LocationImage.svelte';
    import Bevel from '../layout/Bevel.svelte';
    import { navigateLink } from '../../store/router';

    const hrefFor = (locationUrl: string) => `/week/${locationUrl}`;
</script>

{#each locations as location (location.id)}
    <div class={styles.container}>
        <Bevel match={false} />
        <LocationImage name={location.url} />
        <a
            class={styles.link}
            href={hrefFor(location.url)}
            on:click={(e) => navigateLink(e, hrefFor(location.url))}
        >
            <span>{location.role}</span>
            <span>{location.label}</span>
        </a>
    </div>
{/each}

// src/features/location/Location.tsx
import { Link, useLocation } from 'react-router-dom';
import { locations } from './locations';
import styles from './Location.module.css';
import { LocationImage } from './LocationImage';
import { Bevel } from '../../app/layout/Bevel';

export const Location = () => {
    const { pathname } = useLocation();

    const checkString = (value: string) => {
        return value === 'location' || value === 'week' || value === 'today';
    };

    return (
        <>
            {
                locations.map(location => (
                    <div className={ styles.container } key={ location.id }>
                        <Bevel match={false} />
                        <LocationImage name={ location.url } />
                        <Link
                            className={ styles.link }
                            to={ `/${ checkString(pathname) ? pathname : 'week' }/${ location.url}` }
                        >
                            <span>{ location.role }</span>
                            <span>{ location.label }</span>
                        </Link>
                    </div>
                ))
            }
        </>
    );
};
